FROM python:3.10-slim

WORKDIR /app

# Copy and install
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app files
COPY multi_tool_agent/ ./multi_tool_agent
COPY wsgi.py .

ENV PORT 8080

# Use gunicorn to serve the Flask app
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "wsgi:app", "--workers", "1"]
